name: fyp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  fpdart: ^1.1.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  image_picker: ^0.8.5+3
  image_picker_widget: ^2.1.3
  meta: ^1.11.0
  supabase_flutter: ^2.3.4
  uuid: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - flutter_assets/assets/
